In [ ]:
import numpy as np

In [ ]:
p = np.array([[6,5,3,1],[3,6,2,2],[3,4,3,1]])
p

array([[6, 5, 3, 1],
       [3, 6, 2, 2],
       [3, 4, 3, 1]])

In [ ]:
c = np.array([[1.5, 1.0], [2., 2.5], [5.,4.5], [16.,17.]])
c

array([[ 1.5,  1. ],
       [ 2. ,  2.5],
       [ 5. ,  4.5],
       [16. , 17. ]])

In [ ]:
np.argmin(p@c, axis=1)

array([1, 0, 0])